### ISSUE TITLE
ServiceLevel Plugin does not work with newest version of PHP (since 5.4)

### ISSUE THREAD

**Issue by benlec** [mantisbt-plugins/ServiceLevel#1]
Test on PHP 5.5

Error:
[04-Nov-2013 10:47:14 Europe/Paris] PHP Fatal error:  Call-time pass-by-reference has been removed in C:\inetpub\wwwroot\mantisbt-1.2.15\plugins\ServiceLevel\pages\evaluation_api.php on line 323

Line of code
evaluation_helper_summarize_all_sub_projects($t_project, $p_cache, &$total_sum);

The problem is because since PHP 5.4 pass-by reference is deprecated and your are using this in your code

See here:
http://www.php.net/manual/en/language.references.pass.php
http://stackoverflow.com/questions/8971261/php-5-4-call-time-pass-by-reference-easy-fix-available

The fix is to remove the "&" from the 3rd parameter call in evaluation_helper_summarize_all_sub_projects() method line 323 and 362.

Of course remove it also a Line 344 in Method definition.

**Comment by dregad** [comment]
Note - I did not test this.

> Of course remove it also a Line 344 in Method definition.

Not sure about that one, if you do this then the client does not get the updated variable in return.

**Comment by benlec** [comment]
Well i don't really know because if i let the "&" in Method definition or not, I'm not able to make the plugin work anyways. I know i don't have a PHP Error in the Log file anymore for sure but MANTIS send me this when i click on the EVALUATION page from the Main screen

APPLICATION ERROR #1502
Category not found.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

I tried this: http://mantisbt.org/docs/master-1.2.x/en/administration_guide/admin.troubleshooting.html#ADMIN.TROUBLESHOOTING.ERRORS.1502

But I'm not in this situation, I didn't delete anything. I'm in a testing environment where i have 2 project and 2 or 3 categories... i didn't delete the General one nor any other.....

I don't know if it's related with the Plugin code directly or not.

**Comment by mgodoy** [comment]
Hello Benlec,

I'm getting the same message, Can you fix it?
Also, I have read a lot of post about this, but doesn't work.

Thanks in advance.

**Comment by benlec** [comment]
Hello,
I was not able to fix it.
I gave up

Envoyé de mon iPhone
